services:
  app:
    build:
      context: ./spring-boot-demo
      args:
        APP_NAME: spring-demo-backend
    container_name: spring-demo
    ports:
      - "${SERVER_PORT_APP:-18080}:8080"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_VERSION=${APP_VERSION}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CACHE_TTL=${APP_CACHE_TTL:-300}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - demo-net

  auth:
    build:
      context: ./auth-service
      args:
        APP_NAME: auth-service-jwt
    container_name: auth-service
    ports:
      - "${SERVER_PORT_AUTH:-18081}:8081"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CACHE_TTL=${AUTH_CACHE_TTL:-60}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXP_MS=${ACCESS_TOKEN_EXP_MS:-900000}
      - REFRESH_TOKEN_EXP_MS=${REFRESH_TOKEN_EXP_MS:-604800000}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - demo-net

  nginx:
    build: ./nginx
    container_name: nginx-gateway
    ports:
      - "${NGINX_PORT:-28080}:80"
    depends_on:
      - app
      - auth
    restart: unless-stopped
    networks:
      - demo-net

  postgres:
    image: postgres:16-alpine
    container_name: demo-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${PG_PORT:-15432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - demo-net

  redis:
    image: redis:7-alpine
    container_name: demo-redis
    ports:
      - "${REDIS_PORT:-16379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped
    networks:
      - demo-net

volumes:
  pgdata:

networks:
  demo-net:
    driver: bridge
